### ISSUE TITLE
[Request] Translate to Chinese

### ISSUE THREAD

**Issue by PencilMario** [Rubiksman78/MonikA.I#19]
This is amazing work, can I translate it into Chinese and post it? I will mark the link to your repository.

**Comment by Rubiksman78** [comment]
Sure, I would be pleased to see my work used elsewhere ! If you could credit my repository that would be great too.
Just be careful about the TTS model because it is completely in English and there are not a lot of well supported ones doing Chinese voice cloning. Same for character.ai, the models are in English so you would need some module doing automatic translation or directly using a chinese model.

**Comment by PencilMario** [comment]
I understand, thank you :)
