### ISSUE TITLE
executable isn't opening

### ISSUE THREAD

**Issue by aequitias** [Rubiksman78/MonikA.I#36]
when i double click maim.exe it opens and instantly closes :(

**Comment by Rubiksman78** [comment]
You can try opening it by:
- Right clicking in the folder where the terminal is
- Select Open Terminal Here
- Write `./main.exe` in it and then Enter

Then you'll see in details what is going on and you can report what is the exact issue here.

**Comment by aequitias** [comment]
well so i searched for terminal (english is not my 1st language so i kinda didnt know what you meant) my windows versionis 7 and i cant install windows terminal. Then i searched the file on cmd but it doesnt say anything

**Comment by Rubiksman78** [comment]
You should have something like this when you hold <kbd>Shift</kbd> + <kbd>Right click</kbd>, it should work in Windows 7 too:

![image](https://user-images.githubusercontent.com/66365083/217865798-8b828440-2fda-4e6d-a331-d40542232242.png)

Select this icon and you'll have a terminal window, there is no such installation of windows terminal because it is already integrated with the OS.

**Comment by Rubiksman78** [comment]
I will close this issue for now for inactivity, feel free to reopen it.
